language: node_js                                                             
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
script:
  - npm run lint
  - npm run coverage
  - ./travis.sh
cache:
  directories:
    - node_modules
